version: '3.8'

services:
  # --------------------
  # Base de datos (compartida)
  # --------------------
  db:
    image: postgres:15
    container_name: prosthetic-db
    restart: always
    environment:
      POSTGRES_USER: prosthetic_user
      POSTGRES_PASSWORD: prosthetic_user_123
      POSTGRES_DB: prosthetic_api
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - prosthetic-net

  # --------------------
  # Backend Producción
  # --------------------
  backend:
    build:
      context: ../api/prosthetic-api
    image: prosthetic-backend:latest  # 🆕
    container_name: prosthetic-backend
    restart: always
    depends_on:
      - db
    env_file:
      - ../api/prosthetic-api/.env
    ports:
      - "3000:3000"
    networks:
      - prosthetic-net

  # --------------------
  # Frontend Producción
  # --------------------
  frontend:
    build:
      context: ../front/prosthetic-front
      args:
        ENV_FILE: .env
    image: prosthetic-frontend:latest  # 🆕
    container_name: prosthetic-frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - ../front/prosthetic-front/.env
    ports:
      - "8080:80"
    networks:
      - prosthetic-net

volumes:
  db-data:

networks:
  prosthetic-net:
