version: '3.8'

services:
  # --------------------
  # Base de datos (compartida)
  # --------------------
  db:
    image: postgres:15
    container_name: prosthetic-db
    restart: always
    environment:
      POSTGRES_USER: prosthetic_user
      POSTGRES_PASSWORD: prosthetic_user_123
      POSTGRES_DB: prosthetic_api
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - prosthetic-net

  # --------------------
  # Backend Producción
  # --------------------
  backend:
    build:
      context: ../api/prosthetic-api
    container_name: prosthetic-backend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ../api/prosthetic-api/.env
    ports:
      - "3000:3000"
    networks:
      - prosthetic-net

  # --------------------
  # Backend Preproducción
  # --------------------
  backend-pre:
    build:
      context: ../api/prosthetic-api
    container_name: prosthetic-backend-pre
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ../api/prosthetic-api/.env.pre
    ports:
      - "3100:3000"
    networks:
      - prosthetic-net

volumes:
  db-data:

networks:
  prosthetic-net:
